add_executable(dobby_e2e main.cc)
target_link_libraries(dobby_e2e PRIVATE dobby_static)
target_compile_features(dobby_e2e PRIVATE cxx_std_17)
add_test(NAME dobby_e2e COMMAND dobby_e2e)
if(ANDROID)
  add_library(dobby_e2e_jni SHARED main.cc)
  target_compile_definitions(dobby_e2e_jni PRIVATE DOBBY_E2E_JNI)
  target_link_libraries(dobby_e2e_jni PRIVATE dobby_static log)
  target_compile_features(dobby_e2e_jni PRIVATE cxx_std_17)
endif()

if(DOBBY_GENERATE_SHARED)
  add_executable(dobby_e2e_shared main.cc)
  target_link_libraries(dobby_e2e_shared PRIVATE dobby)
  target_compile_features(dobby_e2e_shared PRIVATE cxx_std_17)
  add_test(NAME dobby_e2e_shared COMMAND dobby_e2e_shared)
  if(WIN32)
    add_custom_command(TARGET dobby_e2e_shared POST_BUILD
      COMMAND ${CMAKE_COMMAND} -E copy_if_different $<TARGET_FILE:dobby> $<TARGET_FILE_DIR:dobby_e2e_shared>)
  endif()
endif()
